### ISSUE TITLE
[RFE] provide information on 'fixability' of reported vulnerabilities

### ISSUE THREAD

**Issue by McFoggy** [sonatype/ossindex-maven#10]
just read your email announce on maven list and just tried your awesome plugin.

As you asked for feedback, here is mine.

It would be IMHO very useful to have information on the possibility or not to resolve the vulnerability i.e. if it exists or not an upper version of the culprit library/plugin that resolves the vulnerability.
As this could take more time for the plugin to answer, perhaps an activation behind a flag/parameter could be foreseen.

As an example I tried it on , [jgitver](https://github.com/jgitver/jgitver-maven-plugin), one of my maven plugin, it reports the following:
```
[ERROR]   org.codehaus.plexus:plexus-utils:jar:3.0.8:compile; https://ossindex.sonatype.org/component/maven:org.codehaus.plexus/plexus-utils@3.0.8
[ERROR]     * Possible XML Injection (0.0); https://ossindex.sonatype.org/vuln/53d58c08-d32b-4d21-92f4-d0930e6b3210
[ERROR]     * Directory traversal in org.codehaus.plexus.util.Expand (0.0); https://ossindex.sonatype.org/vuln/a2f46413-d41e-46e3-9864-d89d15b433be
```
but from there, I do not know if I need to spend time in trying to find a newer version of `plexus-utils` that could resolve the vulnerability or if no newer version resolving the issues exist.

So additionally to the reported vulnerabilities you could probably also report something like:
```
[INFO]   update to org.codehaus.plexus:plexus-utils:jar:3.1.0 to resolve 2 vulnerabilities
```

You could also imagine to report that no newer version resolve the vulnerabilities or if you were numbering/labeling the reported vulnerabilities the message could be for partial fixes:
```
[ERROR]     * Possible XML Injection (0.0) [1]; https://ossindex.sonatype.org/vuln/53d58c08-d32b-4d21-92f4-d0930e6b3210
...
[INFO]   org.codehaus.plexus:plexus-utils:jar:3.1.0 resolves 1 vulnerability on 2: [1]
```

**Comment by jdillon** [comment]
if/when the data is available this will be considered
