### ISSUE TITLE
Document relationship with OSSIndex/ossindex-maven-plugin

### ISSUE THREAD

**Issue by ewanmellor** [sonatype/ossindex-maven#11]
This plugin has the same name, and same apparent purpose, as https://github.com/OSSIndex/ossindex-maven-plugin.  At first glance, they look to be completely independent projects, though I don't know that for sure.

This is doubly confusing because this one looks to be newer, but has version 1.0.0, whereas the other one is at 2.3.8.  When googling, it is very easy to land on the other project on Maven Central (https://mvnrepository.com/artifact/net.ossindex/ossindex-maven-plugin/2.3.8)

Please document the relationship between the two projects -- which one people should be using and why, and clarify the name conflict.

**Comment by jdillon** [comment]
Thanks for the feedback.  Yes we probably should update the new version of the plugin to `3.0.0`, and as we talked about yesterday @ken-duck update the old plugin site to indicate its deprecated and point to the new plugin; and probably add a small node on the new docs to indicate the existence of the old deprecated plugin?

**Comment by ken-duck** [comment]
Agreed. I will endeavour to update the "legacy" plugin's docs and information as soon as possible. The `3.0.0` version number is almost certainly the way to go to help with the confusion.

**Comment by jdillon** [comment]
version 3.0.0 is out, legacy plugin is updated with refs.
