### ISSUE TITLE
Is there a way to DEBUG usage of authId?

### ISSUE THREAD

**Issue by vveider** [sonatype/ossindex-maven#45]
I've added `server id` to `settings.xml` with OSSIndex registration info and added `-Dossindex.authId` to parameters when run maven command.
I've enabled debug for maven build, but had no luck in finding any info about whether this option was applied or not.

Can you help me please?

**Comment by jdillon** [comment]
ATM it looks like there is no positive DEBUG log when authId is flipped on, though you can see more details of he client by configuring Maven logging with this parameter:

    -Dorg.slf4j.simpleLogger.log.org.sonatype.ossindex=DEBUG

There is WARN logging if the given authId doesn't have a <server> defined or that element is missing a username/password however:

* https://github.com/sonatype/ossindex-maven/blob/master/maven-plugin/src/main/java/org/sonatype/ossindex/maven/plugin/AuditMojoSupport.java#L282

To see what is being used for authentication you need to enable the HttpClient logging and check the request's `Authorization` header with this parameter:

    -Dorg.slf4j.simpleLogger.log.org.apache.http.wire=DEBUG

**Comment by vveider** [comment]
Thanks, @jdillon. Will try that.
