### ISSUE TITLE
What's the advantage of running this as part of enforcer vs using the plugin directly?

### ISSUE THREAD

**Issue by astubbs** [sonatype/ossindex-maven#60]
Can't see any comparison on the website, and it's not obvious. Perhaps some people prefer to just have everything ~like this in one plugin...

**Comment by bkrahl-nli** [comment]
It can let your build fail if you are using a known to be vulnerable dependency and thereby raises attention to potential security vulnerabilities in your application.

**Comment by delanym** [comment]
You can fail the build anyway using the plugin. What you cant do with the rule is output a report file.

**Comment by astubbs** [comment]
> What you cant do with the rule is output a report file.

Bingo ok. So actually there's no advantage - in fact it's perhaps more useful to use it as a plugin directly, not through enforcer.

**Comment by astubbs** [comment]
@bkrahl-nli sorry I should have been more clear in my question

**Comment by jdillon** [comment]
@astubbs I believe its mostly user-preference, if you prefer to use maven-enforcer you may want to configure the rule, otherwise if you prefer to use a plugin-execution you can do that too.
