### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by delanym** [sonatype/ossindex-maven#62]
I see the API was updated to match the latest enforcer API but a release has not been made.
Even the current artifact released on Maven Central  is not reflected in https://github.com/sonatype/ossindex-maven/releases

**Comment by ndonewar** [comment]
Thanks for the note! Yes, the project needed some attention as it had not been released in a few years. The 3.2.0 release, which includes the changes you referenced, is out now:
https://github.com/sonatype/ossindex-maven/releases
