### ISSUE TITLE
quiet out-of-scope

### ISSUE THREAD

**Issue by delanym** [sonatype/ossindex-maven#65]
When I specify the scope of the audit through cvssScoreThreshold/scope/transitive I don't want to hear about anything out-of-scope, but the enforcer rule logs a warning for each.

Please add a quiet property in the config to silence these.

**Comment by jdillon** [comment]
@delanym can you provide an example of the output you are talking about?

Maybe its this which you are referring to https://github.com/sonatype/ossindex-maven/blob/main/common/src/main/java/org/sonatype/ossindex/maven/common/ComponentReportAssistant.java#L227 ?

**Comment by delanym** [comment]
@jdillon its actually https://github.com/sonatype/ossindex-maven/blob/a8013d2bcda3b888a9573460b28b32bd655baf05/common/src/main/java/org/sonatype/ossindex/maven/common/ComponentReportAssistant.java#L222

**Comment by jdillon** [comment]
thx @delanym; I don't see any reason why these `warn` logs couldn't (or shouldn't) be `debug`  and thus not show up by default in the output unless `-X` is enabled.

**Comment by jdillon** [comment]
@delanym https://github.com/sonatype/ossindex-maven/pull/67 should resolve your issues, lemme know if there was more you found was too loud by default when excluding.

**Comment by delanym** [comment]
Thanks that's much better
